# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -Idrivers/media/video/msm
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss/pproc/cpp
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss/msm_buf_mgr/

obj-$(CONFIG_MSM_FD) += msm_fd_dev.o msm_fd_hw.o
