#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.
focaltech-objs := focaltech_core.o focaltech_ex_fun.o focaltech_ex_mode.o focaltech_flash.o focaltech_gesture.o focaltech_esdcheck.o focaltech_i2c.o focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT8719)   +=  focaltech.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT8719)   +=  focaltech_flash/
obj-$(CONFIG_TOUCHSCREEN_FTS_FT8719)   +=  focaltech_test/
