# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
