# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-oss/sensor/io
obj-$(CONFIG_MSM_CCI) += msm_cci.o
