# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Novatek NT36xxx touchscreen driver.
#

obj-$(CONFIG_TOUCHSCREEN_NT36XXX) += nt36xxx.o
obj-$(CONFIG_TOUCHSCREEN_NT36XXX_FW_UPDATE) += nt36xxx_fw_update.o
